language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;